<a href="https://colab.research.google.com/github/smiling-koala/data-science-toolkit/blob/main/Tutorial_3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [6]:
import numpy as np
# 1. Create a numpy array of size 2 x 2
print("--- 1. 2x2 Array ---")
array_2x2 = np.zeros((2, 2), dtype=int)
print(f"**2x2 Array**:\n{array_2x2}\n")

# 2. Create a random numpy array of size 3 x 4
print("--- 2. Random 3x4 Array ---")
random_3x4 = np.random.rand(3, 4)
print(f"**Random 3x4 Array**:\n{random_3x4}\n")

# 3. Create a numpy array of ones and a numpy array of zeroes
print("--- 3. Array of Ones and Array of Zeroes ---")
ones_array = np.ones((2, 3), dtype=int)
print(f"**Ones Array (2x3)**:\n{ones_array}")
zeros_array = np.zeros((4, 1), dtype=int)
print(f"**Zeroes Array (4x1)**:\n{zeros_array}\n")

# 4. Create a random numpy array of size 6x3 and transpose it
print("--- 4. Random 6x3 Array and Transpose ---")
original_6x3 = np.random.randint(10, size=(6, 3))
print(f"Original 6x3 Array:\n{original_6x3}")
transposed_array = original_6x3.T
print(f"**Transposed 3x6 Array**:\n{transposed_array}\n")


# 5. Create two random numpy arrays of size n x p and p x m and then compute the dot product
print("--- 5. Dot Product of n x p and p x m Arrays ---")
n = 3
p = 2
m = 4
A = np.random.randint(1, 5, size=(n, p))
print(f"Array A ({n}x{p}):\n{A}")
B = np.random.randint(1, 5, size=(p, m))
print(f"Array B ({p}x{m}):\n{B}")
dot_product = A @ B
print(f"**Dot Product A @ B ({n}x{m})**:\n{dot_product}")

--- 1. 2x2 Array ---
**2x2 Array**:
[[0 0]
 [0 0]]

--- 2. Random 3x4 Array ---
**Random 3x4 Array**:
[[0.70113525 0.91104625 0.3407491  0.84478958]
 [0.29622683 0.18741493 0.43220742 0.46354162]
 [0.49068955 0.33724484 0.37181978 0.25607285]]

--- 3. Array of Ones and Array of Zeroes ---
**Ones Array (2x3)**:
[[1 1 1]
 [1 1 1]]
**Zeroes Array (4x1)**:
[[0]
 [0]
 [0]
 [0]]

--- 4. Random 6x3 Array and Transpose ---
Original 6x3 Array:
[[5 6 3]
 [5 4 3]
 [2 8 0]
 [4 7 2]
 [6 2 4]
 [2 9 8]]
**Transposed 3x6 Array**:
[[5 5 2 4 6 2]
 [6 4 8 7 2 9]
 [3 3 0 2 4 8]]

--- 5. Dot Product of n x p and p x m Arrays ---
Array A (3x2):
[[3 4]
 [1 1]
 [4 2]]
Array B (2x4):
[[1 3 3 4]
 [4 3 1 3]]
**Dot Product A @ B (3x4)**:
[[19 21 13 24]
 [ 5  6  4  7]
 [12 18 14 22]]
